### ISSUE TITLE
Choose language

### ISSUE THREAD

**Issue by lterfloth** [sveinbjornt/hear#10]
It would be nice if one could chose from one of the available languages. Is that planned? :-)

**Comment by KorayUlusan** [comment]
See the man page

```
     -l --language lang
              Specify speech recognition language (locale). Default is 'en-US'.
```

**Comment by espetro** [comment]
Hi, I tried to run `hear -l en-US` but it tells me that `No file at path en-US`. However, running just `hear` works. Do you know what might be happening?
