### ISSUE TITLE
Continuous dictation only works on Apple Silicon M1

### ISSUE THREAD

**Issue by RobBW** [sveinbjornt/hear#11]
Submitted for the record.
I've just had a frustrating few hours getting _hear_ going in Monterey 12.5.1. Its a neat piece of work.
If you have the same issue it is not Sveinbjornt's problem, it is caused by Apple not supporting continuous dictation in older Intel based Macs. 

See: [https://discussions.apple.com/thread/253318311](url) 
> Please see [macOS Monterey - New Features.](https://www.apple.com/macos/monterey/features/) The availability of this feature is limited to Macs with the M1 chip. Does your Mac mini have the M1?

Perhaps a comment could be added to the installation notes to avoid more frustrated users?

The limitation could be subverted by automatically breaking the input audio file into less than 30(or is it 60) second chunks. A task for someone cleverer than me.

**Comment by sveinbjornt** [comment]
You should be able to use the -d flag for continuous on-device dictation. At least it works on my 16" Intel MBP (2020) running macOS 12.6.
