### ISSUE TITLE
Translate from audio output

### ISSUE THREAD

**Issue by espetro** [sveinbjornt/hear#12]
Hi, I'm interested in using hear for Speech Recognition when I have a call via e.g. FaceTime, Microsoft Teams or Google Meet. Most of these apps already have a recognition feature, but mostly it's for English only. 

Do you know if it's possible to use the audio output, instead of the audio input, as source for `hear`?

**Comment by sveinbjornt** [comment]
This would require a kernel extension, I'm afraid, so it's not going to happen. But of course it might be possible to support it via a pre-existing solution e.g. SoundFlower.

**Comment by scottleibrand** [comment]
You can also do this using Rogue Amoeba's Loopback. I have it set up to create an audio device that loops back Zoom's audio output, which I can then set as the device for sound input in Apple's Sound preferences to get `hear` to transcribe what is being said on Zoom.
