### ISSUE TITLE
Supported language not finding file

### ISSUE THREAD

**Issue by ronnyworm** [sveinbjornt/hear#16]
First things first: I love this tool!

It's working great for the english language. Maybe I'm using it wrong but I would expect this to return german text (if german text was spoken):
`hear -l de-DE`
Instead I'm getting: `No file at path de-DE`

I reassured that this language is supported by executing `hear -s` (the list contains de-DE).

Where am I supposed to save what file exactly? Or how should I call `hear -l` ?

**Comment by sveinbjornt** [comment]
There was a bug in version 0.1 where the -l flag argument was incorrectly parsed. This is fixed in 0.2. Try upgrading and things should work.

**Comment by ronnyworm** [comment]
Just upgraded, works like a charm!
Thank you so much!!
