### ISSUE TITLE
Abort after starting.

### ISSUE THREAD

**Issue by sunrisewestern** [sveinbjornt/hear#18]
> $ hear
> [1]    25534 abort      hear

**Comment by sveinbjornt** [comment]
Well, that wasn't a very helpful initial issue. What macOS version? What hardware? Have you enabled Siri in Preferences/Settings? Does the issue persist after a restart? Can you run the command "hear -l"?

**Comment by adisidev** [comment]
Thank you for replying to the issue @sveinbjornt . I have the exact same issue. Here is some more information:

I'm on macOS Monterey (12.4 )
I have Siri enabled in Preferences/Settings and have "Enable type to Siri" unchecked under accessibility settings
My computer has an audio input device (default mic), I tried it both with and without the `-m` flag.
The issue indeed persists after a restart too.
I can't run the "hear -i" command either, despite providing it an appropriate file.

The hear --help command works fine, and gives the following output.
```
❯ hear --help
hear version 0.2 by Sveinbjorn Thordarson

hear [-s] [-l lang] [-i file] [-f fmt] [-d]

Options:

    -s --supported          Print list of supported languages

    -l --language           Specify speech recognition language
    -i --input [file_path]  Specify audio file to process
    -f --format [fmt]       Specify audio file format
    -d --device             Only use on-device speech recognition
    -m --mode               Enable single-line output mode (mic only)

    -h --help               Prints help
    -v --version            Prints program name and version

For further details, see 'man hear'.
```

Finally, building from source succeeds, the tests fail and I have the same issues mentioned above when testing the compiled binary.

I'd be happy to jump on a Zoom call to help with debugging.

**Comment by sveinbjornt** [comment]
Thanks for the feedback. What about running "hear -l" (an ell, not an i)?

**Comment by adisidev** [comment]
No, `hear -l` with a provided language, `hear -l en-US` did not work either.

**Comment by adisidev** [comment]
@sveinbjornt By any chance, were you able to recreate the issue? I'm wondering whether it might be a permissions issue somewhere? Or do you suspect it to be something else?

**Comment by sveinbjornt** [comment]
I have not been able to recreate this issue. I'm still on Monterey myself and everything works fine. If I had to guess, this is some kind of permissions issue.

**Comment by adisidev** [comment]
I added instructions on how to fix this in the README on #19

**Comment by sunrisewestern** [comment]
> I added instructions on how to fix this in the README on #19

Thanks. This works on Terminal.app, but not on iTerm2.app.

**Comment by sveinbjornt** [comment]
> Thanks. This works on Terminal.app, but not on iTerm2.app.

So, definitely some weird Apple permissions issue.

**Comment by sunrisewestern** [comment]
Agree. Forgetting to mention, I'm on macOS Ventura 13.1.

**Comment by sveinbjornt** [comment]
Yeah, everyone in this thread is on Ventura except me :). I have to be cautious on account of work.
