### ISSUE TITLE
FR: Automatic punctuation

### ISSUE THREAD

**Issue by anijatsu** [sveinbjornt/hear#22]
With macOS 13 there's been an automatic punctuation function added into the language model.
It seems to be a matter of setting of one property, but I don't even know how to build the program properly, so I'll leave it up to you knowledgeable folks :)
https://developer.apple.com/documentation/speech/sfspeechrecognitionrequest/3930023-addspunctuation?changes=late_1_2

**Comment by sveinbjornt** [comment]
Will add this as a command line flag. However, it is only available in Ventura (13.0+).
