### ISSUE TITLE
kAFAssistantErrorDomain error 203

### ISSUE THREAD

**Issue by JGL** [sveinbjornt/hear#3]
hear -d -l 'en-GB' -i someM4A.m4a > aTranscription.txt 

results in 

Error: The operation couldn’t be completed. (kAFAssistantErrorDomain error 203.)

Running 12.4 (21F79), with en-GB for on device.

**Comment by sveinbjornt** [comment]
Are you still experiencing this with version 0.2? Unable to reproduce. Also, make sure you have Siri enabled in System Preferences/Settings.
