### ISSUE TITLE
`zsh: abort` when running from the IntelliJ built-in terminal

### ISSUE THREAD

**Issue by avernet** [sveinbjornt/hear#4]
Whatever command I run, other than `hear -h` or `hear -v`, I am getting a `zsh: abort` response. For instance:

```
$ hear -m                      
zsh: abort      hear -m
```

Is there something I am missing?

**Comment by sveinbjornt** [comment]
What version of macOS are you running, and on which CPU architecture?

**Comment by avernet** [comment]
I figured what the problem is: this is only happening when running `hear` from the built-in terminal in IntelliJ; all is good when running it from Terminal. This isn't a huge deal, so if this isn't an easy fix, feel free to close this. Thank you!
