### ISSUE TITLE
Option to stop listening after a while

### ISSUE THREAD

**Issue by synox** [sveinbjornt/hear#6]
I wish `hear` could stop automatically, instead of staying active. Maybe when there is no more input for 3 seconds, or when reaching a user-defined text length?

In my simple game, the user has to say back the word. 
```bash
	say --voice="Samantha"  -- "$word [[slnc 400]]" 
	response=$(hear --mode)

	shopt -s nocasematch
	if [[  "${response}" == "${word}" ]]; then
		echo ✅ $word
	else
		echo 🛑 wrong. ➡  $word
		echo " - press enter for next word -"; read
	fi
```
However pressing CTRL-C to stop the listening it stops the script instead. 

Also for scripting, the ESCAPE-DELETE control characters get into the way. A plain text output when the program is complete would be preffered. The --mode output looks like this
```
[2K
Good[2K
[2K
Good morning
```

Workarounds: 
- stop after 4 seconds: `response=$(timeout 4 hear --mode)`
 - clean string: `response=$(echo "$response" | sed 's/.*\[2K//g' | tr -d '\r\n')`

**Comment by sveinbjornt** [comment]
It's a cool idea, I'll look into adding it.

**Comment by sveinbjornt** [comment]
I have added an exit word option, i.e. if you run "hear -x 'quit'", the transcription session will end as soon as you say the word 'quit'. That might help with your use case.

**Comment by sveinbjornt** [comment]
Btw, as for control characters, they are only emitted in single-line mode, which is intended for presentation in a terminal client. Omit the "--mode" flag if you don't want them.

**Comment by synox** [comment]
Thanks!
