### ISSUE TITLE
Integrate with ffmpeg?

### ISSUE THREAD

**Issue by sagz** [sveinbjornt/hear#7]
Hi, great utility! Any way to integrate this with ffmpeg to be able to auto-subtitle videos? Maybe there's a piping command that could make this work today, but I'm not able to figure that out.

**Comment by sveinbjornt** [comment]
Apple's speech recognition API does not provide any timestamps so this is not gonna work.

**Comment by sagz** [comment]
Could this be done where in ffmpeg sends cut up snippets of audio and those snippets are sent to `hear`?

Issue is if it cuts in the middle of a word. Maybe the cutting can be made to be aware of silence. That's likely out of scope.
